{application,project2_bonus,
             [{applications,[kernel,stdlib,elixir,logger]},
              {description,"project2_bonus"},
              {modules,['Elixir.Gossip','Elixir.MasterNode',
                        'Elixir.Project2Bonus','Elixir.PushSum',
                        'Elixir.Topology']},
              {registered,[]},
              {vsn,"0.1.0"},
              {extra_applications,[logger]}]}.
